// This file was automatically generated by /supp/autogen.

#include "../worldgenapi.h"

const WorldGenAPI::Functions &WorldGenAPI::functions() {
	static const Functions fs = [] {
		Functions fs;
		Function f;

		const auto finalize = [&]() {
			f.prototype = Function::composePrototype(f.name, iterator(f.arguments).mapx(x.type).toList());
			fs.list.push_back(f);
			fs.prototypeMapping[f.prototype] = f.id;
			if(!fs.nameSet.contains(f.name))
				fs.nameList.push_back(f.name);
			fs.nameSet.insert(f.name);
			fs.nameMapping[f.name].push_back(f.id);
		};

		f.section = "Utility functions";
f.name = "worldPos";
f.returnValue.name = "pos";
f.arguments.resize(0);
f.description = R"STRING(Returns world position of the currently calculated block.)STRING";f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 0;
finalize();

f.name = "select";
f.returnValue.name = "result";
f.arguments.resize(3);
f.arguments[0].name = "cond";
f.arguments[1].name = "thn";
f.arguments[2].name = "els";
f.description = R"STRING(If `cond` is `true`, returns `thn`, else returns `els`.)STRING";f.arguments[0].type = WGA_Value::ValueType::Bool;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 1;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float2;
f.arguments[2].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 2;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float3;
f.arguments[2].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 3;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Bool;
f.arguments[2].type = WGA_Value::ValueType::Bool;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 4;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Block;
f.arguments[2].type = WGA_Value::ValueType::Block;
f.returnValue.type = WGA_Value::ValueType::Block;
f.id = 5;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Rule;
f.arguments[2].type = WGA_Value::ValueType::Rule;
f.returnValue.type = WGA_Value::ValueType::Rule;
f.id = 6;
finalize();

f.arguments[1].type = WGA_Value::ValueType::ComponentNode;
f.arguments[2].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::ComponentNode;
f.id = 7;
finalize();

f.section = "Vector functions";
f.name = "float2";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "x";
f.arguments[1].name = "y";
f.description = R"STRING(Constructs a 2-dimensional vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 8;
finalize();

f.name = "float2";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.description = R"STRING(Constructs a 2-dimensional vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 9;
finalize();

f.name = "float3";
f.returnValue.name = "r";
f.arguments.resize(3);
f.arguments[0].name = "x";
f.arguments[1].name = "y";
f.arguments[2].name = "z";
f.description = R"STRING(Constructs a 3-dimensional vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 10;
finalize();

f.name = "float3";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "xy";
f.arguments[1].name = "z";
f.description = R"STRING(Constructs a 3-dimensional vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 11;
finalize();

f.name = "float3";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.description = R"STRING(Constructs a 3-dimensional vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 12;
finalize();

f.name = "x";
f.returnValue.name = "x";
f.arguments.resize(1);
f.arguments[0].name = "vec";
f.description = R"STRING(Returns the `x` component of a vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 13;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 14;
finalize();

f.name = "y";
f.returnValue.name = "y";
f.arguments.resize(1);
f.arguments[0].name = "vec";
f.description = R"STRING(Returns the `y` component of a vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 15;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 16;
finalize();

f.name = "z";
f.returnValue.name = "x";
f.arguments.resize(1);
f.arguments[0].name = "vec";
f.description = R"STRING(Returns the `z` component of a vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 17;
finalize();

f.name = "xy";
f.returnValue.name = "xy";
f.arguments.resize(1);
f.arguments[0].name = "vec";
f.description = R"STRING(Returns the `x` and `y` components of a vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 18;
finalize();

f.name = "normalize";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.description = R"STRING(Returns the vector normalized.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 19;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 20;
finalize();

f.name = "length";
f.returnValue.name = "len";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.description = R"STRING(Returns euclidean length of a vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 21;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 22;
finalize();

f.name = "lengthExp";
f.returnValue.name = "len";
f.arguments.resize(2);
f.arguments[0].name = "v";
f.arguments[1].name = "exp";
f.description = R"STRING(Returns length of a vector with the dimensional exponent being `exp` (1 = manhattan, 2 = euclidean).)STRING";f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 23;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 24;
finalize();

f.name = "manhattanLength";
f.returnValue.name = "dist";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.description = R"STRING(Returns manhattan length of a vector.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 25;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 26;
finalize();

f.name = "distance";
f.returnValue.name = "dist";
f.arguments.resize(2);
f.arguments[0].name = "vec1";
f.arguments[1].name = "vec2";
f.description = R"STRING(Returns euclidean distance between two vectors.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 27;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 28;
finalize();

f.name = "manhattanDistance";
f.returnValue.name = "dist";
f.arguments.resize(2);
f.arguments[0].name = "vec1";
f.arguments[1].name = "vec2";
f.description = R"STRING(Returns manhattan distance between two vectors.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 29;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 30;
finalize();

f.name = "distanceTo";
f.returnValue.name = "dist";
f.arguments.resize(1);
f.arguments[0].name = "targetWorldPos";
f.description = R"STRING(Returns distance from the current block to `targetWorldPos` (in world coordinates).)STRING";f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 31;
finalize();

f.name = "distanceTo";
f.returnValue.name = "dist";
f.arguments.resize(1);
f.arguments[0].name = "targetWorldPos";
f.description = R"STRING(Returns distance from the current block to `targetWorldPos` (in world coordinates).)STRING";f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 32;
finalize();

f.name = "distanceTo2D";
f.returnValue.name = "dist";
f.arguments.resize(1);
f.arguments[0].name = "targetWorldPos";
f.description = R"STRING(Returns distance from the current block to `targetWorldPos` (in world coordinates). Only considers X and Y coordinates.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 33;
finalize();

f.name = "distanceToLine";
f.returnValue.name = "dist";
f.arguments.resize(3);
f.arguments[0].name = "p";
f.arguments[1].name = "a";
f.arguments[2].name = "b";
f.description = R"STRING(Returns distance of the point `p` to a line defined by points `a` and `b`.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.arguments[2].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 34;
finalize();

f.section = "Sampling functions";
f.name = "sampleOffset";
f.returnValue.name = "valueAtOffset";
f.arguments.resize(2);
f.arguments[0].name = "variable";
f.arguments[1].name = "offset";
f.description = R"STRING(Returns value of `variable` sampled on a world position of (`worldPos() + offset`).)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 35;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 36;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 37;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Bool;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 38;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Block;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Block;
f.id = 39;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Rule;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Rule;
f.id = 40;
finalize();

f.arguments[0].type = WGA_Value::ValueType::ComponentNode;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::ComponentNode;
f.id = 41;
finalize();

f.name = "sampleAt";
f.returnValue.name = "valueAtPos";
f.arguments.resize(2);
f.arguments[0].name = "variable";
f.arguments[1].name = "worldPos";
f.description = R"STRING(Returns value of `variable` sampled on the given world position. The position doesn't have to be constant.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 42;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 43;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 44;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Bool;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 45;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Block;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Block;
f.id = 46;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Rule;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Rule;
f.id = 47;
finalize();

f.arguments[0].type = WGA_Value::ValueType::ComponentNode;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::ComponentNode;
f.id = 48;
finalize();

f.name = "sampleAt";
f.returnValue.name = "valueAtPos";
f.arguments.resize(2);
f.arguments[0].name = "variable";
f.arguments[1].name = "worldPos";
f.description = R"STRING(Returns value of `variable` sampled on the given world position. The position doesn't have to be constant.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 49;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 50;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 51;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Bool;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 52;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Block;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Block;
f.id = 53;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Rule;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Rule;
f.id = 54;
finalize();

f.arguments[0].type = WGA_Value::ValueType::ComponentNode;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::ComponentNode;
f.id = 55;
finalize();

f.name = "sampleGradient2D";
f.returnValue.name = "gradient";
f.arguments.resize(2);
f.arguments[0].name = "value";
f.arguments[1].name = "dist";
f.description = R"STRING(Returns 2D gradient of `value`, calculated as `float2(val[x + dist] - val[x - dist], val[y + dist] - val[y - dist]) / (1 + dist * 2)`)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 56;
finalize();

f.name = "sampleAvg2D";
f.returnValue.name = "avg";
f.arguments.resize(2);
f.arguments[0].name = "value";
f.arguments[1].name = "dist";
f.description = R"STRING(Samples at offsets (0,0), (dist,0), (-dist,0), (0,dist) and (0,-dist) and returns the average.`)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 57;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 58;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 59;
finalize();

f.section = "Biome functions";
f.name = "biomeParam_nearest";
f.returnValue.name = "var";
f.arguments.resize(1);
f.arguments[0].name = "var";
f.description = R"STRING(**This function cannot be used in the WOGLAC language. There is a special syntax construct for biome params.**

Returns value of variable $var of the nearest biome.
)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 60;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 61;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 62;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Bool;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 63;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Block;
f.returnValue.type = WGA_Value::ValueType::Block;
f.id = 64;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Rule;
f.returnValue.type = WGA_Value::ValueType::Rule;
f.id = 65;
finalize();

f.arguments[0].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::ComponentNode;
f.id = 66;
finalize();

f.name = "biomeParam_nearestSet";
f.returnValue.name = "var";
f.arguments.resize(1);
f.arguments[0].name = "var";
f.description = R"STRING(**This function cannot be used in the WOGLAC language. There is a special syntax construct for biome params.**

Returns value of variable $var of the nearest biome that has the variable set.
)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 67;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 68;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 69;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Bool;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 70;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Block;
f.returnValue.type = WGA_Value::ValueType::Block;
f.id = 71;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Rule;
f.returnValue.type = WGA_Value::ValueType::Rule;
f.id = 72;
finalize();

f.arguments[0].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::ComponentNode;
f.id = 73;
finalize();

f.name = "biomeParam_weighted";
f.returnValue.name = "var";
f.arguments.resize(2);
f.arguments[0].name = "var";
f.arguments[1].name = "exp";
f.description = R"STRING(**This function cannot be used in the WOGLAC language. There is a special syntax construct for biome params.**

Returns value of variable $var weighted across surrounding biomes. The $exp adjusts exponent for the individual weights (1 = linear interpolation).
)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 74;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 75;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 76;
finalize();

f.section = "Structure functions";
f.name = "spawn2D";
f.returnValue.name = "result";
f.arguments.resize(5);
f.arguments[0].name = "entryRule";
f.arguments[1].name = "maxRadius";
f.arguments[2].name = "seed";
f.arguments[3].name = "spawnZ";
f.arguments[4].name = "spawnCondition";
f.description = R"STRING(Creates a structure procgen pass and returns generated blocks (block.undefined on places where nothing was generated to differentiate from generated block.air). Structures can expand up to `maxRadius` chunks from the entry chunk. For each (x, y, `spawnZ`) point in space, the `entryRule` is expanded if `spawnCondition` is `true`.)STRING";f.arguments[0].type = WGA_Value::ValueType::Rule;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.arguments[3].type = WGA_Value::ValueType::Float;
f.arguments[4].type = WGA_Value::ValueType::Bool;
f.returnValue.type = WGA_Value::ValueType::Block;
f.id = 77;
finalize();

f.name = "worldPos";
f.returnValue.name = "worldPos";
f.arguments.resize(1);
f.arguments[0].name = "node";
f.description = R"STRING(Returns position of the provided component node in global world coordinates (only usable in structure generation).)STRING";f.arguments[0].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 78;
finalize();

f.name = "worldPos";
f.returnValue.name = "worldPos";
f.arguments.resize(1);
f.arguments[0].name = "localPos";
f.description = R"STRING(Transforms world component-local position to world position.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 79;
finalize();

f.name = "localPos";
f.returnValue.name = "localPos";
f.arguments.resize(0);
f.description = R"STRING(Returns component-local position.)STRING";f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 80;
finalize();

f.name = "localPos";
f.returnValue.name = "localPos";
f.arguments.resize(1);
f.arguments[0].name = "worldPos";
f.description = R"STRING(Transforms world position to component-local position.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 81;
finalize();

f.name = "localSeed";
f.returnValue.name = "seed";
f.arguments.resize(0);
f.description = R"STRING(Returns component-local seed.)STRING";f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 82;
finalize();

f.name = "distanceTo";
f.returnValue.name = "dist";
f.arguments.resize(1);
f.arguments[0].name = "node";
f.description = R"STRING(Returns distance from the current block to the provided component node.)STRING";f.arguments[0].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 83;
finalize();

f.name = "sampleAt";
f.returnValue.name = "valueAtNodePos";
f.arguments.resize(2);
f.arguments[0].name = "variable";
f.arguments[1].name = "node";
f.description = R"STRING(Returns value of `variable` sampled on position of the given node.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 84;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 85;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 86;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Bool;
f.arguments[1].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 87;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Block;
f.arguments[1].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::Block;
f.id = 88;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Rule;
f.arguments[1].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::Rule;
f.id = 89;
finalize();

f.arguments[0].type = WGA_Value::ValueType::ComponentNode;
f.arguments[1].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::ComponentNode;
f.id = 90;
finalize();

f.section = "Noise functions";
f.name = "randC";
f.returnValue.name = "result";
f.arguments.resize(1);
f.arguments[0].name = "seed";
f.description = R"STRING(Returns random value in range [0,1], constant everywhere.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 91;
finalize();

f.name = "randL";
f.returnValue.name = "result";
f.arguments.resize(1);
f.arguments[0].name = "seed";
f.description = R"STRING(Returns random value in range [0,1], constant everywhere. Incorporates local seed of the currently generated structure (works similarly to `randC(localSeed() + seed)`).)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 92;
finalize();

f.name = "randPC";
f.returnValue.name = "result";
f.arguments.resize(1);
f.arguments[0].name = "seed";
f.description = R"STRING(Returns random value in range [0,1], different for each chunk.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 93;
finalize();

f.name = "rand2D";
f.returnValue.name = "result";
f.arguments.resize(1);
f.arguments[0].name = "seed";
f.description = R"STRING(Returns random value in range [0,1], different for every column.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 94;
finalize();

f.name = "rand3D";
f.returnValue.name = "result";
f.arguments.resize(1);
f.arguments[0].name = "seed";
f.description = R"STRING(Returns random value in range [0,1], different for every block.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 95;
finalize();

f.name = "valueNoisePC";
f.returnValue.name = "result";
f.arguments.resize(3);
f.arguments[0].name = "scale";
f.arguments[1].name = "seed";
f.arguments[2].name = "nodeValue";
f.description = R"STRING(Linearly interpolates between values at node points that are determined by `nodeValue`. $scale has to be a whole number >= 1 or things might not work properly.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 96;
finalize();

f.name = "valueNoise2D";
f.returnValue.name = "result";
f.arguments.resize(3);
f.arguments[0].name = "scale";
f.arguments[1].name = "seed";
f.arguments[2].name = "nodeValue";
f.description = R"STRING(Linearly interpolates between values at node points that are determined by `nodeValue`. $scale has to be a whole number >= 1 or things might not work properly.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 97;
finalize();

f.name = "perlin2D";
f.returnValue.name = "result";
f.arguments.resize(2);
f.arguments[0].name = "scale";
f.arguments[1].name = "seed";
f.description = R"STRING(Returns 2D Perlin noise value in range [-1,1]. $scale has to be a whole number >= 1 or things might not work properly.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 98;
finalize();

f.name = "perlin3D";
f.returnValue.name = "result";
f.arguments.resize(2);
f.arguments[0].name = "scale";
f.arguments[1].name = "seed";
f.description = R"STRING(Returns 3D Perlin noise value in range [-1,1]. $scale has to be a whole number >= 1 or things might not work properly.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 99;
finalize();

f.name = "voronoi2D";
f.returnValue.name = "result";
f.arguments.resize(4);
f.arguments[0].name = "scale";
f.arguments[1].name = "seed";
f.arguments[2].name = "resultType";
f.arguments[3].name = "metricExponent";
f.description = R"STRING(Returns 2D Voronoi-diagram based value. Use `metricExponent = 2` for standard euclidean metric
* `resultType=0` -> distance to the edge (2ndDist-1stDist)
* `resultType=1` -> distance to the nearest point (1stDist)
* `resultType=2` -> 1stDist / 2ndDist

$scale has to be a whole number >= 1 or things might not work properly.
)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.arguments[3].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 100;
finalize();

f.name = "voronoi2DColored";
f.returnValue.name = "result";
f.arguments.resize(5);
f.arguments[0].name = "scale";
f.arguments[1].name = "seed";
f.arguments[2].name = "resultType";
f.arguments[3].name = "metricExponent";
f.arguments[4].name = "coloring";
f.description = R"STRING(Same as voronoi2D, except each node now accepts `coloring`; there are no edges between nodes of the same color. For that to work, there are special `resultType` values:
* `resultType=10` -> weighted distance from center
* `resultType=11` -> nearest point coloring
* `resultType=12` -> weighted distance from border

$scale has to be a whole number >= 1 or things might not work properly.
)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.arguments[3].type = WGA_Value::ValueType::Float;
f.arguments[4].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 101;
finalize();

f.name = "poissonDisc2DBool";
f.returnValue.name = "isNode";
f.arguments.resize(2);
f.arguments[0].name = "seed";
f.arguments[1].name = "radius";
f.description = R"STRING(Spreads points pseudorandomly on the 2D plane. Each point has a `radius` (2D dimensionality) that can be between 1 and 16. Distance of any two points is not less than sum of their radii. Returns true if there is a point on the current position or false if there isn't.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 102;
finalize();

f.name = "osimplex2D";
f.returnValue.name = "result";
f.arguments.resize(2);
f.arguments[0].name = "scale";
f.arguments[1].name = "seed";
f.description = R"STRING(Returns 2D OpenSimplex 2 noise value in range [-1,1]. Implemented using FastNoise2 lib.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 103;
finalize();

f.name = "osimplex3D";
f.returnValue.name = "result";
f.arguments.resize(2);
f.arguments[0].name = "scale";
f.arguments[1].name = "seed";
f.description = R"STRING(Returns 3D OpenSimplex 2 noise value in range [-1,1]. Implemented using FastNoise2 lib.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 104;
finalize();

f.section = "Aggregation functions";
f.name = "minPC";
f.returnValue.name = "minVal";
f.arguments.resize(1);
f.arguments[0].name = "val";
f.description = R"STRING(Returns minimum value of `val` across the entire chunk. Expects `val` to have `2D` dimensionality.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 105;
finalize();

f.name = "maxPC";
f.returnValue.name = "maxVal";
f.arguments.resize(1);
f.arguments[0].name = "val";
f.description = R"STRING(Returns maximum value of `val` across the entire chunk. Expects `val` to have `2D` dimensionality.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 106;
finalize();

f.section = "Math functions";
f.name = "min";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.description = R"STRING(Returns minimum of the two values.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 107;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 108;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 109;
finalize();

f.name = "max";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.description = R"STRING(Returns maximum of the two values.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 110;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 111;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 112;
finalize();

f.name = "smoothMin";
f.returnValue.name = "r";
f.arguments.resize(3);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[2].name = "k";
f.description = R"STRING(Returns smoothed minimum of the two values with smoothing radius `k`.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 113;
finalize();

f.name = "smoothMax";
f.returnValue.name = "r";
f.arguments.resize(3);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[2].name = "k";
f.description = R"STRING(Returns smoothed maximum of the two values with smoothing radius `k .)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 114;
finalize();

f.name = "clamp";
f.returnValue.name = "r";
f.arguments.resize(3);
f.arguments[0].name = "v";
f.arguments[1].name = "min";
f.arguments[2].name = "max";
f.description = R"STRING(Returns value `v` limited to bounds [`min–max`].)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 115;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.arguments[2].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 116;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.arguments[2].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 117;
finalize();

f.name = "clamp01";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.description = R"STRING(Returns value `v` limited to bounds [0-1].)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 118;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 119;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 120;
finalize();

f.name = "mix";
f.returnValue.name = "r";
f.arguments.resize(3);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[2].name = "p";
f.description = R"STRING(Returns `a * (1 - p) + b * p`.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.arguments[2].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 121;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.arguments[2].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 122;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.arguments[2].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 123;
finalize();

f.name = "abs";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.description = R"STRING(Returns absolute value of the parameter)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 124;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 125;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 126;
finalize();

f.name = "floor";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 127;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 128;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 129;
finalize();

f.name = "ceil";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 130;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 131;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 132;
finalize();

f.name = "round";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 133;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 134;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 135;
finalize();

f.name = "fract";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.description = R"STRING(Returns fractional part of the number `x - trunc(x)`.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 136;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 137;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 138;
finalize();

f.name = "ffract";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "v";
f.description = R"STRING(Returns fractional part of the number `x - floor(x)`.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 139;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 140;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 141;
finalize();

f.name = "pow";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "v";
f.arguments[1].name = "e";
f.description = R"STRING(Returns power of `v` to the exponent `e`.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 142;
finalize();

f.name = "sin";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "x";
f.description = R"STRING(Returns `sin(x)`, `x` is in radians.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 143;
finalize();

f.name = "cos";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "x";
f.description = R"STRING(Returns `cos(x)`, `x` is in radians.)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 144;
finalize();

f.section = "Basic math functions";
f.name = "inverse";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "a";
f.description = R"STRING(Returns negative value of the argument (`-a`).)STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 145;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 146;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 147;
finalize();

f.name = "add";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 148;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 149;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 150;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 151;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 152;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 153;
finalize();

f.name = "sub";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 154;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 155;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 156;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 157;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 158;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 159;
finalize();

f.name = "mult";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 160;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 161;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 162;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 163;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 164;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 165;
finalize();

f.name = "div";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 166;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 167;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 168;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 169;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 170;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 171;
finalize();

f.name = "mod";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.description = R"STRING(Floating point modulo (C++ fmod))STRING";f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 172;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float;
f.id = 173;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 174;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float2;
f.id = 175;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 176;
finalize();

f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Float3;
f.id = 177;
finalize();

f.section = "Basic logic functions";
f.name = "logOr";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Bool;
f.arguments[1].type = WGA_Value::ValueType::Bool;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 178;
finalize();

f.name = "logAnd";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Bool;
f.arguments[1].type = WGA_Value::ValueType::Bool;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 179;
finalize();

f.name = "logNot";
f.returnValue.name = "r";
f.arguments.resize(1);
f.arguments[0].name = "a";
f.arguments[0].type = WGA_Value::ValueType::Bool;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 180;
finalize();

f.name = "bool";
f.returnValue.name = "b";
f.arguments.resize(1);
f.arguments[0].name = "a";
f.description = R"STRING(Converts to bool (returns `true` if the block is not `block.undefined`, even with air.))STRING";f.arguments[0].type = WGA_Value::ValueType::Block;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 181;
finalize();

f.section = "Comparison functions";
f.name = "compEq";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 182;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 183;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 184;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Bool;
f.arguments[1].type = WGA_Value::ValueType::Bool;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 185;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Block;
f.arguments[1].type = WGA_Value::ValueType::Block;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 186;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Rule;
f.arguments[1].type = WGA_Value::ValueType::Rule;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 187;
finalize();

f.arguments[0].type = WGA_Value::ValueType::ComponentNode;
f.arguments[1].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 188;
finalize();

f.name = "compEq";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 189;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 190;
finalize();

f.name = "compNeq";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 191;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float2;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 192;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float3;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 193;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Bool;
f.arguments[1].type = WGA_Value::ValueType::Bool;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 194;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Block;
f.arguments[1].type = WGA_Value::ValueType::Block;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 195;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Rule;
f.arguments[1].type = WGA_Value::ValueType::Rule;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 196;
finalize();

f.arguments[0].type = WGA_Value::ValueType::ComponentNode;
f.arguments[1].type = WGA_Value::ValueType::ComponentNode;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 197;
finalize();

f.name = "compNeq";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float2;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 198;
finalize();

f.arguments[0].type = WGA_Value::ValueType::Float3;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 199;
finalize();

f.name = "compLt";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 200;
finalize();

f.name = "compGt";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 201;
finalize();

f.name = "compLeq";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 202;
finalize();

f.name = "compGeq";
f.returnValue.name = "r";
f.arguments.resize(2);
f.arguments[0].name = "a";
f.arguments[1].name = "b";
f.arguments[0].type = WGA_Value::ValueType::Float;
f.arguments[1].type = WGA_Value::ValueType::Float;
f.returnValue.type = WGA_Value::ValueType::Bool;
f.id = 203;
finalize();


		return fs;
	} ();
	return fs;
}
